kcp-dev/api-syncagent

.golangci.yml
.prow.yaml
hack/ci/verify.sh
hack/download-tool.sh

This adds some basic Prowjobs to check PRs before merging.
```release-note
NONE
```

✨ add prowjobs

---

Dockerfile

No need to label the temporary builder image.
```release-note
NONE
```

🐛 set labels on the final container image

---

cmd/api-syncagent/main.go
cmd/api-syncagent/options.go

Some more advanced deployment scenarios for kcp-api-syncagent may require overriding the host and CA used in the REST config for the local Kubernetes cluster.
This can be the case when an OIDC trust exists between two clusters in which one cluster should run the syncagent, but another cluster is the control plane to which objects should be synced from kcp. In those situations, we want to reuse the token discovered from the container filesystem and talk to a different server which also accepts our token.
Fixes #
```release-note
Add `--kubeconfig-host-override` and `--kubeconfig-ca-file-override` flags
```

:sparkles: Add kubeconfig-host-override and kubeconfig-ca-file-override flags

---

cmd/api-syncagent/main.go
cmd/api-syncagent/options.go
deploy/crd/kcp.io/syncagent.kcp.io_publishedresources.yaml
docs/README.md
docs/getting-started.md
docs/publish-resources.md
internal/controller/apiexport/controller.go
internal/controller/apiexport/doc.go
internal/controller/apiresourceschema/controller.go
internal/controller/apiresourceschema/doc.go
internal/controller/sync/doc.go
internal/controller/syncmanager/controller.go
internal/controller/syncmanager/doc.go
internal/projection/projection.go
internal/sync/syncer.go
internal/sync/syncer_related.go
sdk/apis/syncagent/v1alpha1/published_resource.go

Platform is a leftover from the codebase's previous home and is now kind of a confusing term. I was debating with myself whether a more generic term might be good, like "source", but ultimately the syncer expects the source not to be any kind of Kubernetes endpoint, but a kcp or at least kcp-like endpoint, so the concrete term "kcp" feels okay.
```release-note
Reword "platform" to "kcp"
```

🌱 Reword "platform" to "kcp"

---

cmd/api-syncagent/main.go
internal/controller/sync/controller.go
internal/controller/syncmanager/controller.go
internal/sync/state_store.go
internal/sync/state_store_test.go
internal/sync/syncer.go
internal/sync/syncer_test.go

The agent can run in any namespace and the hardcoded namespace was a leftover form the old Servlet code.
```release-note
Move object states Secrets to the namespace where the agent is running.
```

⚠️ move object states Secrets to the namespace where the agent is running

---

.prow.yaml
Dockerfile

This updates to Go 1.23.5 as preparation for a first 0.1.0 release.
Fixes #
```release-note
Container image is now built with Go 1.23.5
```

:seedling: Update to Go 1.23.5 for builds and tests

---

docs/README.md
docs/consuming-services.md
docs/faq.md
docs/getting-started.md

This removes the old Helm-based RBAC setup and explains how to do it nowadays. Plus it adds an FAQ section to the docs.
```release-note
NONE
```

📖 update documentation

---

deploy/crd/kcp.io/syncagent.kcp.io_publishedresources.yaml
go.mod
go.sum
internal/controller/sync/controller.go
internal/controller/syncmanager/lifecycle/cluster.go
internal/sync/context.go
internal/sync/context_test.go
internal/sync/meta.go
internal/sync/meta_test.go
internal/sync/object_syncer.go
internal/sync/state_store.go
internal/sync/syncer.go
internal/sync/syncer_test.go
internal/sync/types.go
sdk/apis/syncagent/v1alpha1/published_resource.go
sdk/applyconfiguration/syncagent/v1alpha1/publishedresourcespec.go

This PR adds a new option to PublishedResources: `enableWorkspacePaths`. When set to true, the syncer will put the kcp workspace _path_ as an additional annotation on the synced objects.
Fixes #11
```release-note
Add `spec.enableWorkspacePaths` to PublishedResources to enable storing the kcp workspace path (e.g. "root:myorg:team1") as an annotation on the synced objects in the service cluster.
```

✨ Add workspace paths as annotations to synced objects

---

cmd/api-syncagent/main.go
docs/getting-started.md
internal/controller/sync/controller.go
internal/controller/syncmanager/controller.go
internal/sync/object_syncer.go
internal/sync/syncer.go
internal/sync/syncer_related.go
internal/sync/syncer_test.go
internal/sync/types.go

If two or more Sync Agents work on the same local cluster (but each talking to its own kcp), _and_ they both serve the same local API (i.e. there are 2 PublishedResources that describe the same local API), they will get confused over each other's objects. When Agent 1 syncs an object from kcp 1 to the local cluster, Agent 2 might think it own it. The severity of this issue also depends on object naming (if for example the kcp cluster names are included in the local object names, for example as namespaces, then a collision is less likely since cluster names should be globally unique).
To improve the situation, this PR uses the already existing agent name to label local objects, declaring ownership over them. This does not mean 2 PublishedResources can now lead to conflicts (object A in kcp …

✨ Label local objects with the agent name

---

internal/controller/apiresourceschema/controller.go

Keeping off the discussion regarding how new versions should mature, we decided that for now we just pretend each CRD only has one version in it. This is "more compatible" than requring existing CRDs to define conversion rules.
Fixes #20
```release-note
NONE
```

🐛 drop all non-selected versions from CRDs when creating APIResourceSchemas

---

cmd/api-syncagent/main.go
cmd/api-syncagent/options.go
docs/faq.md
go.mod
internal/controller/apiresourceschema/controller.go
test/crds/backup.yaml
test/crds/crontab-improved.yaml
test/crds/crontab-multi-versions.yaml
test/e2e/apiexport/apiexport_test.go
test/e2e/apiresourceschema/apiresourceschema_test.go
test/utils/fixtures.go
test/utils/process.go
test/utils/utils.go

#22 made it possible, so now this PR adds more e2e tests. And I also identified the first few bugs in the agent thanks to the tests :-)
In addition to the tests, this PR also extends the FAQ because I saw many temporary errors in the agent log files, but when I checked, they were indeed temporary. Also I checked, an APIExport gets ready & virtualWorkspaceURLsReady immediately after creation, so there isn't really anything the agent could do to delay its own setup and wait for the APIs to be actually available.
There are now also flags to configure the metrics & health probes servers.
part of #16
```release-note
* Fix CRD version projection not actually changing the API version in the APIResourceSchema.
* Fix agent not setting served/storage in the API version in the APIResourceSchema.
* …
```

🌱 Add integration tests for the apiexport controller

---

hack/ci/run-e2e-tests.sh
internal/controller/apiexport/controller.go
internal/controller/sync/controller.go
internal/sync/object_syncer.go
test/e2e/sync/primary_test.go
test/utils/process.go
test/utils/wait.go

This PR adds 3 new tests for the bare minimum syncing logic: No related objects, no mutations, just copy from kcp to envtest. And even with that, I randomly discovered that we never implemented the resource filtering support, which this PR now fixes.
part of #16
```release-note
* Implement `spec.filter` in a PublishedResource to filter out unwanted remote objects (i.e. objects in kcp).
* Fix errors in log because of race condition when creating namespaces.
```

🌱 Add first tests for the syncing logic

---

docs/README.md
docs/getting-started.md

fix the incorrect link
Fixes #
```release-note
NONE
```

📖  (docs): fix the link

---

.github/workflows/release.yml
.gitignore
.goreleaser.yaml
Makefile

This PR adds:
- GoReleaser config based on [the kcp's GoRelease config](https://github.com/kcp-dev/kcp/blob/dfcda9f9ec7922dd7360f98811b1025b2542a8d2/.goreleaser.yaml)
- Release GitHub action based on [the kcp's release GH action](https://github.com/kcp-dev/kcp/blob/dfcda9f9ec7922dd7360f98811b1025b2542a8d2/.github/workflows/goreleaser.yml)
The api-syncagent's GH action uses `actions/upload-artifact@v4` instead of `cytopia/upload-artifact-retry-action@v0.1.7` as the latter is unmaintained (see https://github.com/kcp-dev/kcp/issues/3309).
```release-note
NONE
```
/assign @xrstf @mjudeikis

:sparkles: Add GoReleaser config and Release GitHub Action

---

internal/discovery/client.go

When refactoring the CRD discovery to use OpenAPI schemas, I decided Kraft meiner Wassersuppe (viel Spaß beim Googlen) that we do not need the CRD-based discovery anymore, because why have 2 mechanisms that both result in a CRD?
Well, CRDs contain more useful data than the OpenAPI schema. This begins with the custom path expression on subresources (like the scale subresource) and ends at additional printer columns. Also, loads of other validation rules would get lost when relying only on the OpenAPI schema:
To fix this, I aligned the code more with kcp, which already has a "prefer CRD, fallback to OpenAPI" mentality. Our code here is still a bit but noticeably different from kcp because we do not export the storage version necessarily, but whatever version is defined in the …

🐛 prefer CRDs when discovery API types, as CRDs contain more betterer information

---

internal/controller/apiresourceschema/controller.go
internal/crypto/hash.go
internal/projection/naming.go
internal/sync/meta.go
internal/sync/metadata.go
internal/sync/object_syncer.go
internal/sync/state_store.go
internal/sync/syncer.go
internal/sync/syncer_related.go
internal/sync/syncer_test.go
internal/sync/types.go
test/e2e/sync/primary_test.go

Objects in Kubernetes can have names up to 253 characters in length. However label values must not be longer than 63 characters. Since the agent uses the remote (kcp) name/namespace as labels, the syncing failed when objects with names longer than 63 characters were in kcp.
This PR fixes that by hashing the namespace/name and storing the original names, for reference, as annotations instead. The same issue affected the secret store, because keys in a secret's data must also not be overly long, so the agent now uses hashes for these as well.
Existing synced objects will not be found under this new implementation, but the agent will already automatically "adopt" existing objects and re-label/annotate them as needed. The data in the store secrets will also be recreated, so effectively every …

🐛 Handle long object names

---

internal/controller/syncmanager/lifecycle/cluster.go
internal/sync/metadata.go
internal/sync/object_syncer.go
test/e2e/sync/related_test.go

This PR fixes two issues:
* fixes #41: since #15 syncing related resources back to the kcp workspace was broken because the remote client (i.e. the kcp client) did not use a scheme with core/v1 in it, so the agent did not know about namespaces.
* fixes #35: sync-related labels were not stripped from related resources. This is now fixed for simple usecases and for others we still need more tests.
```release-note
* Fix syncing related resources that originate on the service cluster.
* Fix stripping sync-related labels and annotations from related resources.
```

🐛 Fix labels on related resources, fix syncing related resources, add first e2e test

---

docs/getting-started.md

The api-syncagent [gets the `LogicalCluster`](https://github.com/kcp-dev/api-syncagent/blob/v0.2.0/cmd/api-syncagent/main.go#L227) to resolve the logical cluster name and path. However, this is not reflected in the `ClusterRole` described in the "Getting Started" guide. Additionally, if we create the `APIExport` for the api-syncagent in a workspace other than root, we also need to explicitly grant the user access to it.
This PR adds the missing RBAC rule to the existing `ClusterRole` and an additional `ClusterRoleBinding` to grant the access to the workspace.
```release-note
NONE
```

:book: docs: add missing RBAC bindings / rules

---

.github/workflows/gh-pages.yaml
docs/content/publish-resources.md

Adding github workflow to publish docs markdown files as gh-pages. Similar to what is done in https://github.com/kcp-dev/contrib
/kind documentation
https://github.com/kcp-dev/api-syncagent/issues/26
Fixes #
N/A
```release-note
NONE
```

docs: add workflow for publishing docs to gh-pages

---

.prow.yaml

Same as https://github.com/kcp-dev/kcp/pull/3398.
/kind cleanup
Fixes #
```release-note
NONE
```

Update prow jobs to infra/build:1.23.7-2 image for ARM64 support

---

.github/workflows/release.yml

The docs workflow already does the same :)
/kind cleanup
```release-note
Update to Go 1.23.7.
```

pin Github actions in release workflow, update release pipeline to Go 1.23.7

---

.gimps.yaml
.golangci.yml
Makefile
internal/discovery/client.go

One of the less painful golangci-lint 2 migrations I have seen and done in the last few weeks.
/kind chore
```release-note
NONE
```

update golangci-lint to 2.1.6

---

.github/workflows/docs-gen-and-push.yaml
.github/workflows/release.yml
.prow.yaml
Dockerfile

#66 needs sha3, so we need the agent to use Go 1.24.
/kind feature
```release-note
Update to Go 1.24.3
```

bump to Go 1.24.3

---

docs/content/publish-resources/index.md

One of the examples was still using the old style of templating logic.
/kind documentation
```release-note
NONE
```

fix example in label selector renaming

---

README.md
docs/content/contributing/releasing.md

Noticed this in https://github.com/kcp-dev/kcp-operator/pull/60: https://github.com/kcp-dev/infra/blob/48b16067ca1bead2922eb87e3f9d8207b641a737/prow/jobs/kcp-dev/api-syncagent/api-syncagent-postsubmits.yaml#L11
Bumping the badges to link to the correct destination as well.
/kind documentation
Fixes #
```release-note
NONE
```

Fix release branch naming scheme and badge links

---

deploy/crd/kcp.io/syncagent.kcp.io_publishedresources.yaml
internal/sync/syncer_related.go
sdk/apis/syncagent/v1alpha1/published_resource.go

References are still kind of useful and compact. In a future version we want to allow to configure related resources where 1 primary object can contain references to many related objects (but the admin only configures 1). Since Go templates only ever result in a string, references suddenly offer a new advantage: The ability to select _and return_ multiple values at once.
/kind documentation
```release-note
NONE
```

Undeprecate references

---

docs/content/publish-resources/index.md
docs/generators/crd-ref/crd.template.md
internal/sync/syncer_related.go
test/crds/backup.go
test/crds/backup.yaml
test/e2e/sync/related_test.go

So far the agent has 3 different modes for finding related objects:
* references
* templates
* label selectors
Only label selectors were currently able to handle many objects for 1 single related object configuration. This proved a bit too limitting.
This PR extends references to also allow to select multiple values. For this a query would look like `spec.users.#.name` to select all the names of all users in an object.
/kind feature
```release-note
References can now return lists of values to allow a single related resource configuration to match many Kubernetes objects at once.
```

Allow references to select multiple values

---

.prow.yaml
Makefile
cmd/api-syncagent/kcp.go
cmd/api-syncagent/main.go
cmd/api-syncagent/options.go
docs/content/getting-started.md
docs/content/publish-resources/index.md
internal/controller/syncmanager/controller.go
test/e2e/sync/apiexportendpointslice_test.go
test/utils/fixtures.go
test/utils/process.go
test/utils/utils.go

This implements support for APIExportEndpointSlices (AEES).
Starting with kcp 0.28, APIExports do not contain the virtual workspace URLs anymore (unless you specify a feature flag on kcp, and we certainly do not want to make that required for running the Agent). Instead in 0.28+, kcp will automatically create an AEES for each new APIExport, using the same name as the export.
In kcp 0.27, admins *can* manually create an AEES for their APIExport, but are not forced to because kcp still makes the URLs available in the APIExport.
To handle each and every situation, the agent now simply supports both scenarios. You can run it like before with `--apiexport-ref` if you're still on 0.27, or you can use `--apiexportendpointslice-ref` when you are in kcp 0.28+ or you make use of custom AEES in 0.27 …

Support APIExportEndpointSlices / kcp 0.28

---

Makefile

This makes it much easier to use debuggers to connect to an agent. Simply build with `DEBUG_BUILD=1 make` and bam, done.
/kind feature
```release-note
NONE
```

allow to set $DEBUG_BUILD to build a binary with debugging symbols

---

Makefile
internal/controller/apiexport/controller.go
internal/controller/apiexport/reconciler.go
internal/controller/syncmanager/controller.go
test/e2e/sync/primary_test.go
test/utils/fixtures.go

PublishedResources have a flag to enable fetching the logicalcluster and determining the workspace path of a remote object. However enabling this flag didn't actually work because
* logicalclusters were not claimed in the APIExport
* core.kcp.io/v1alpha1 was not added to the client's scheme
This PR rectifies both problems and adds a basic testcase to ensure it works.
/kind bug
```release-note
Fix `EnableWorkspacePaths` in PublishedResources not having any visible effect, fix missing permission claim for logicalclusters.
```

Fix support for workspace paths

---

internal/controller/sync/controller.go

It looks like an unmanaged controller (in controller-rutime? or multicluster-runtime?) doesn't log its reconciler errors unless you pass a logger into it. Thus, tons of errors are swallowed without any indication why.
/kind bug
Fixes #
```release-note
Correctly log reconciler errors for object sync
```

Pass a logger to unmanaged sync controller to surface reconcile errors

---

internal/sync/templating/naming.go
internal/sync/templating/related.go

This is required since functions like sha3 short expect a string to work properly and not the custom type
/kind bug
Fixes #
```release-note
Fix: ClusterName and ClusterPath can now be used in conjunction with sha3short template function 
```

use strings instead of custom types when passing to templating
